all: main

main: holeydtcount.o holeydtcount_test.cpp doctest.h
	g++ -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wuseless-cast -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Weffc++ -std=c++17 -o main holeydtcount.o holeydtcount_test.cpp

test: holeydtcount.o test.cpp
	g++ holeydtcount.o test.cpp -o test

holeydtcount.o: holeydtcount.cpp holeydtcount.hpp
	g++ -Wall -Wextra -Wshadow -Wnon-virtual-dtor -pedantic -Wold-style-cast -Wcast-align -Wunused -Woverloaded-virtual -Wpedantic -Wconversion -Wsign-conversion -Wmisleading-indentation -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wnull-dereference -Wuseless-cast -Wdouble-promotion -Wformat=2 -Wimplicit-fallthrough -Weffc++ -std=c++17 -c holeydtcount.cpp


clean:
	rm -f main

.PHONY: all clean
